pipeline {
  agent { label 'dev04' }

  environment {
    APP_NAME          = 'post-slovenia-ingestor'
    DOCKER_TAG        = 'latest'
    DOCKER_REG        = 'harbor.trace.rid-intrasoft.eu'
    DOCKER_REPO       = 'postslovenia-di'
    DOCKER_REG_CREDS  = 'harbor-jenkins-creds'
    COMPOSE_FILE      = 'docker-compose.yml'
  }

  stages {
    stage('Build') {
      steps {
        sh """
          docker build -t ${APP_NAME}:${DOCKER_TAG} .
        """
      }
    }

    stage('Push to Harbor') {
      steps {
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${DOCKER_REG_CREDS}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){
                echo "***** Push Docker Image *****"
                sh 'docker compose build'
                sh 'docker login ${DOCKER_REG} -u ${USERNAME} -p ${PASSWORD}'
                sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}'
                sh 'DOCKER_TAG="latest" docker compose build'
                sh 'docker image push ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:latest'
          }
      }
    }

    stage('Deploy with Docker Compose') {
      steps {
        sh """
          docker compose -f ${COMPOSE_FILE} down --remove-orphans
          docker compose -f ${COMPOSE_FILE} up -d --build
        """
      }
    }
  }

  post {
    success { echo 'Deployment completed successfully!' }
    failure { echo 'Deployment failed. Check logs for details.' }
  }
}
